### PR TITLE
Convert secrets with specific shapes into pull secrets

### PR DESCRIPTION
**Pull request by smarterclayton**
Recognize mounted secrets of the standard form as pull secrets so the image
controllers and other tools can leverage them. Only sets the type.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@stevekuznetsov this will allow us to add a `--secret-dir .../pullsecret` and have it recognized.  However, I'm going to need to update release to create a secret with the appropriate keys (registry-pull-credentials-quay.io has a key `config.json` which doesn't match what Kube expects) by updating populate secrets to create a ci-operator-pull-secrets secret with the correct `.dockerconfigjson` key.

**Comment by smarterclayton** [comment]
Blocks OCP jobs now that ci-operator imports the image vs just referencing.  Also, binary mode was wrong so I fixed that (caught it while debugging)

**Comment by smarterclayton** [comment]
Tagging to unblock OCP, will react if there are any issues.

**Comment by stevekuznetsov** [comment]
Nice, this is minimal

**Pull request merged**
