### PR TITLE
Test with docker socket

### PR DESCRIPTION
**Pull request by gabemontero**
So this PR moves the needle forward wrt item 1 from https://github.com/openshift/release/pull/947#issue-195288298

In conjunction, I've added commit https://github.com/openshift/release/pull/947/commits/6ceb088396fe11573266da8f77e32196fdcbf708 to the sample ci-operator config json file, to provide an example of how these changes are leveraged.

So the high level flow is:
- check out a given git spec as part of constructing the "src" IST
- for the jenkins scenario, there is not "make build"... etc. to create a binary
- we skip to the "image" steps, which level ci-operator's docker build strategy support, to build the various centos images out of the jenkins repo
- these changes then add:
  a) the ability to link a test step with the image step, where that test step takes the IST as input and sets a specified env var to the docker pull spec for the specified test command to leverage
  b) the test will also be linked to the output image tag step created for the image step based on the presence of the tag_specification stanza ... the tagging to the stable image stream will no longer occur unless the test passes
  c) also added fields to the test step to set the privileged bit and mount the docker socket (jenkins unit tests need that)

Of course, the use of c) does not work at the moment, as there is no scc/sa/role/etc. I can leverage on the api.ci cluster to allow for the creation of privileged pods with the docker socket mounted.  We can discuss that element either here or out of band as folks desire.

Some sample output:
1) running ci-operator against the master.json in https://github.com/openshift/release/pull/947/commits/6ceb088396fe11573266da8f77e32196fdcbf708 as-is produced this output ... note the tagging to the stable image stream does not occur since the tests failed:

```
gmontero ~/go/src/github.com/openshift/release  (ci-oper-jenkins-job)$ ci-operator --config ./ci-operator/config/openshift/jenkins/master.json --namespace=ggm-test-namespace --git-ref=openshift/jenkins@master --dry-run=false
2018/07/12 15:22:01 Resolved openshift/jenkins@master to commit 80870e9960e5a729751d2499437f55a272947fe9
2018/07/12 15:22:01 Resolved source https://github.com/openshift/jenkins to master@80870e99
2018/07/12 15:22:01 Resolved https://api.ci.openshift.org/openshift/release:golang-1.9 to sha256:7e01c72ab5a214f784bf134829c5c70c2da807b9203f457be18bbd5b7b5019a1
2018/07/12 15:22:01 Resolved https://api.ci.openshift.org/openshift/origin-v3.11:base to sha256:d5b7c06d9dffc43c3ba691b9030831bbed7f5609f2b36279f97cfe0932b345c7
2018/07/12 15:22:01 Running [input:root], [input:base], [release-inputs], src, bin-2-centos, bin-slave-base-centos, bin-slave-maven-centos, bin-slave-nodejs-centos, bin-agent-maven-35-centos, bin-agent-nodejs-8-centos, unit-2-centos, unit-slave-base-centos, unit-slave-maven-centos, unit-slave-nodejs-centos, unit-agent-maven-35-centos, unit-agent-nodejs-8-centos, [output:stable:bin-2-centos], [output:stable:bin-slave-base-centos], [output:stable:bin-slave-maven-centos], [output:stable:bin-slave-nodejs-centos], [output:stable:bin-agent-maven-35-centos], [output:stable:bin-agent-nodejs-8-centos], [images]
2018/07/12 15:22:01 Creating namespace ggm-test-namespace
2018/07/12 15:22:01 Namespace will be deleted after 10m0s of idle time
2018/07/12 15:22:02 Tagging release images from openshift/jenkins:${component}
2018/07/12 15:22:02 Tagging https://api.ci.openshift.org/openshift/release:golang-1.9 into pipeline:root
2018/07/12 15:22:02 Tagging https://api.ci.openshift.org/openshift/origin-v3.11:base into pipeline:base
2018/07/12 15:22:02 Building src
2018/07/12 15:22:29 Build src succeeded after 27s
2018/07/12 15:22:29 Building bin-slave-base-centos
2018/07/12 15:22:29 Building bin-2-centos
2018/07/12 15:26:13 Build bin-slave-base-centos succeeded after 3m44s
2018/07/12 15:26:13 Executing test unit-slave-base-centos
2018/07/12 15:26:14 Building bin-slave-maven-centos
2018/07/12 15:26:14 Building bin-agent-nodejs-8-centos
2018/07/12 15:26:14 Building bin-slave-nodejs-centos
2018/07/12 15:26:14 Building bin-agent-maven-35-centos
2018/07/12 15:28:08 Build bin-agent-nodejs-8-centos succeeded after 1m53s
2018/07/12 15:28:08 Executing test unit-agent-nodejs-8-centos
2018/07/12 15:28:38 Build bin-slave-nodejs-centos succeeded after 2m23s
2018/07/12 15:28:38 Executing test unit-slave-nodejs-centos
2018/07/12 15:30:26 Build bin-2-centos succeeded after 7m56s
2018/07/12 15:30:26 Executing test unit-2-centos
2018/07/12 15:32:16 Build bin-agent-maven-35-centos succeeded after 6m1s
2018/07/12 15:32:16 Executing test unit-agent-maven-35-centos
2018/07/12 15:33:20 Build bin-slave-maven-centos succeeded after 7m5s
2018/07/12 15:33:20 Executing test unit-slave-maven-centos
2018/07/12 15:33:21 Ran for 11m19s
error: some steps failed:
  * unable to create pod: pods "unit-slave-base-centos" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
  * unable to create pod: pods "unit-agent-nodejs-8-centos" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
  * unable to create pod: pods "unit-slave-nodejs-centos" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
  * unable to create pod: pods "unit-2-centos" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
  * unable to create pod: pods "unit-agent-maven-35-centos" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
  * unable to create pod: pods "unit-slave-maven-centos" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```

2) If I remove the "required_test" fields from each of my "image" steps, the stable image stream tagging does occur:

```
gmontero ~/go/src/github.com/openshift/release  (ci-oper-jenkins-job)$ ci-operator --config ./ci-operator/config/openshift/jenkins/master.json --namespace=ggm-test-namespace --git-ref=openshift/jenkins@master --dry-run=false
2018/07/12 15:37:21 Resolved openshift/jenkins@master to commit 80870e9960e5a729751d2499437f55a272947fe9
2018/07/12 15:37:21 Resolved source https://github.com/openshift/jenkins to master@80870e99
2018/07/12 15:37:22 Resolved https://api.ci.openshift.org/openshift/release:golang-1.9 to sha256:7e01c72ab5a214f784bf134829c5c70c2da807b9203f457be18bbd5b7b5019a1
2018/07/12 15:37:22 Resolved https://api.ci.openshift.org/openshift/origin-v3.11:base to sha256:d5b7c06d9dffc43c3ba691b9030831bbed7f5609f2b36279f97cfe0932b345c7
2018/07/12 15:37:22 Running [input:root], [input:base], [release-inputs], src, bin-2-centos, bin-slave-base-centos, [output:stable:bin-slave-base-centos], bin-slave-maven-centos, bin-slave-nodejs-centos, bin-agent-maven-35-centos, bin-agent-nodejs-8-centos, unit-2-centos, unit-slave-base-centos, unit-slave-maven-centos, unit-slave-nodejs-centos, unit-agent-maven-35-centos, unit-agent-nodejs-8-centos, [output:stable:bin-2-centos], [output:stable:bin-slave-maven-centos], [output:stable:bin-slave-nodejs-centos], [output:stable:bin-agent-maven-35-centos], [output:stable:bin-agent-nodejs-8-centos], [images]
2018/07/12 15:37:22 Creating namespace ggm-test-namespace
2018/07/12 15:37:22 Namespace will be deleted after 10m0s of idle time
2018/07/12 15:37:24 Tagging release images from openshift/jenkins:${component}
2018/07/12 15:37:24 Tagging https://api.ci.openshift.org/openshift/release:golang-1.9 into pipeline:root
2018/07/12 15:37:24 Tagging https://api.ci.openshift.org/openshift/origin-v3.11:base into pipeline:base
2018/07/12 15:37:25 Building src
2018/07/12 15:37:55 Build src succeeded after 29s
2018/07/12 15:37:55 Building bin-2-centos
2018/07/12 15:37:55 Building bin-slave-base-centos
2018/07/12 15:40:09 Build bin-slave-base-centos succeeded after 2m13s
2018/07/12 15:40:09 Executing test unit-slave-base-centos
2018/07/12 15:40:09 Tagging bin-slave-base-centos into stable
2018/07/12 15:40:09 Building bin-slave-nodejs-centos
2018/07/12 15:40:09 Building bin-agent-maven-35-centos
2018/07/12 15:40:09 Building bin-agent-nodejs-8-centos
2018/07/12 15:40:09 Building bin-slave-maven-centos
2018/07/12 15:41:53 Build bin-agent-nodejs-8-centos succeeded after 1m42s
2018/07/12 15:41:53 Executing test unit-agent-nodejs-8-centos
2018/07/12 15:41:53 Tagging bin-agent-nodejs-8-centos into stable
2018/07/12 15:43:00 Build bin-slave-nodejs-centos succeeded after 2m51s
2018/07/12 15:43:00 Executing test unit-slave-nodejs-centos
2018/07/12 15:43:00 Tagging bin-slave-nodejs-centos into stable
2018/07/12 15:43:23 Build bin-2-centos succeeded after 5m27s
2018/07/12 15:43:23 Executing test unit-2-centos
2018/07/12 15:46:27 Build bin-agent-maven-35-centos succeeded after 6m18s
2018/07/12 15:46:27 Executing test unit-agent-maven-35-centos
2018/07/12 15:46:27 Tagging bin-agent-maven-35-centos into stable
2018/07/12 15:47:01 Build bin-slave-maven-centos succeeded after 6m51s
2018/07/12 15:47:01 Executing test unit-slave-maven-centos
2018/07/12 15:47:01 Tagging bin-slave-maven-centos into stable
2018/07/12 15:47:02 Ran for 9m40s
```

@smarterclayton @stevekuznetsov @bparees ptal

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@gabemontero we built the openshift/ci-vm-operator to allow a test to provision a full VM -- is that preferrable to DinD solution? Also preferrable to exposing docker socket on build nodes to tests, right?

/cc @smarterclayton

**Comment by gabemontero** [comment]
On Thu, Jul 12, 2018 at 4:32 PM, Steve Kuznetsov <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> we built the
> openshift/ci-vm-operator to allow a test to provision a full VM -- is that
> preferrable to DinD solution? Also preferrable to exposing docker socket on
> build nodes to tests, right?
>
was totally unaware of ci-vm-operator  ... I'll take a look and circle back
here accordingly - thanks!

**Comment by gabemontero** [comment]
@stevekuznetsov - is there a docker for `ci-vm-operator` analogous to [to the ci-operator google doc](https://docs.google.com/document/d/11cC-Img4EuEMhySviqTVoeynuWIrjQdMTYzBLeh9g_8/edit?ts=5b075483#heading=h.iky83k9qdryq) ?

I'll dive into the code, but first blush based on that repo's readme connecting to the dots to the flow articulated in the ci-operator doc was not obvious to me.

**Comment by gabemontero** [comment]
OK, took a more detailed pass at ci-vm-operator, and have a semblance of possibles flows from here in my head.

One possible flow:
- since you need `system:admin` to operate, perhas a pool of VMs are pre-created is a separate namespace
- a role exists such that users running `ci-operator` can access the Secrets with the `ssh` connection information
- and thus the test step, if an optional bit is specified, could execute user supplied commands in the VM, where the docker socket exists
- now, the specifics of those *user supplied commands*
  1) in our Jenkins scenario, our metadata for this is 
       a) the docker ref for the IST associated with our newly built Jenkins images in the `pipeline` image stream
       b) the `src` IST has a git checkout of our repo's files, including the test files
       c) the raw test command then includes a prefacing env var set to a), so the tests know which image to use, cd'ing to a context dir to run the test command, and then the actual test command to run

     So do we run pods in the VM, or just raw docker commands that can leverage the available docker socket?

      With the latter, I could see a ssh -c 'docker run -it <docker ref of src IST> < ENV=<docker ref of jenkins img in pipeline IST> <actual test command>

Certainly there are a few permutations of the above flow that are conceivable.

So yeah, I can remove the setting of the privileged bit, mounting of the docker socket, in the api.ci Pod from this PR, assuming my flow above is at least within the ballpark.

I think the gating of tagging images into stable base on the test results on images from the image step is still relevant to our scenario, and still applicable to ci-operator.

But certainly folks can comment here as desired, or if not, hopefully we can dive into this in the Monday PM meeting I sent to invite for.

@stevekuznetsov @bparees @smarterclayton

**Comment by gabemontero** [comment]
OK @smarterclayton @bparees @stevekuznetsov and myself had a pow-wow

we are going to hold tight on this PR for now ... there is a chance that an altered form of this change could be useful

certainly the piece about ci-vm-operator based tests (where those tests need the docker socket, etc.) will initiate from an openshift/release template, not a from ci-operator initiated action against a VM provisioned by ci-vm-operator

**Pull request closed without merging**
