### PR TITLE
Always pull pipeline images

### PR DESCRIPTION
**Pull request by kargakis**
Avoid reusing cached, possibly invalid, images.

~~Fixes https://github.com/openshift/release/issues/2055~~

### CODE REVIEW

**Comment by kargakis** [comment]
I just realized we need to set the policy in our templates. Still useful for ci-operator @stevekuznetsov ?

**Comment by smarterclayton** [comment]
/hold

This should never be a thing.  If you are rebuilding a namespace and overriding pipeline tags you are "doing it wrong" (ci-operator is not intended to rebuild over things in a namespace)

**Comment by kargakis** [comment]
> ci-operator is not intended to rebuild over things in a namespace

This is how ci-operator works

**Comment by kargakis** [comment]
can be a jira card if it needs to change

**Pull request closed without merging**
